// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	ast "github.com/hyperjumptech/grule-rule-engine/ast"
	facts "github.com/jenujari/go-astro-re/facts"

	mock "github.com/stretchr/testify/mock"
)

// DataContextBuilder is an autogenerated mock type for the DataContextBuilder type
type DataContextBuilder struct {
	mock.Mock
}

type DataContextBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *DataContextBuilder) EXPECT() *DataContextBuilder_Expecter {
	return &DataContextBuilder_Expecter{mock: &_m.Mock}
}

// BuildDataContext provides a mock function with given fields: customer, outcome, ruleCtx
func (_m *DataContextBuilder) BuildDataContext(customer *facts.Customer, outcome *facts.ProcessOutcome, ruleCtx facts.RuleContext) (ast.IDataContext, error) {
	ret := _m.Called(customer, outcome, ruleCtx)

	if len(ret) == 0 {
		panic("no return value specified for BuildDataContext")
	}

	var r0 ast.IDataContext
	var r1 error
	if rf, ok := ret.Get(0).(func(*facts.Customer, *facts.ProcessOutcome, facts.RuleContext) (ast.IDataContext, error)); ok {
		return rf(customer, outcome, ruleCtx)
	}
	if rf, ok := ret.Get(0).(func(*facts.Customer, *facts.ProcessOutcome, facts.RuleContext) ast.IDataContext); ok {
		r0 = rf(customer, outcome, ruleCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ast.IDataContext)
		}
	}

	if rf, ok := ret.Get(1).(func(*facts.Customer, *facts.ProcessOutcome, facts.RuleContext) error); ok {
		r1 = rf(customer, outcome, ruleCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DataContextBuilder_BuildDataContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildDataContext'
type DataContextBuilder_BuildDataContext_Call struct {
	*mock.Call
}

// BuildDataContext is a helper method to define mock.On call
//   - customer *facts.Customer
//   - outcome *facts.ProcessOutcome
//   - ruleCtx facts.RuleContext
func (_e *DataContextBuilder_Expecter) BuildDataContext(customer interface{}, outcome interface{}, ruleCtx interface{}) *DataContextBuilder_BuildDataContext_Call {
	return &DataContextBuilder_BuildDataContext_Call{Call: _e.mock.On("BuildDataContext", customer, outcome, ruleCtx)}
}

func (_c *DataContextBuilder_BuildDataContext_Call) Run(run func(customer *facts.Customer, outcome *facts.ProcessOutcome, ruleCtx facts.RuleContext)) *DataContextBuilder_BuildDataContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*facts.Customer), args[1].(*facts.ProcessOutcome), args[2].(facts.RuleContext))
	})
	return _c
}

func (_c *DataContextBuilder_BuildDataContext_Call) Return(_a0 ast.IDataContext, _a1 error) *DataContextBuilder_BuildDataContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DataContextBuilder_BuildDataContext_Call) RunAndReturn(run func(*facts.Customer, *facts.ProcessOutcome, facts.RuleContext) (ast.IDataContext, error)) *DataContextBuilder_BuildDataContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewDataContextBuilder creates a new instance of DataContextBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataContextBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataContextBuilder {
	mock := &DataContextBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
