// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	ast "github.com/hyperjumptech/grule-rule-engine/ast"
	mock "github.com/stretchr/testify/mock"
)

// KnowledgeBaseProvider is an autogenerated mock type for the KnowledgeBaseProvider type
type KnowledgeBaseProvider struct {
	mock.Mock
}

type KnowledgeBaseProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *KnowledgeBaseProvider) EXPECT() *KnowledgeBaseProvider_Expecter {
	return &KnowledgeBaseProvider_Expecter{mock: &_m.Mock}
}

// KnowledgeBase provides a mock function with given fields: tenantID, version
func (_m *KnowledgeBaseProvider) KnowledgeBase(tenantID string, version string) (*ast.KnowledgeBase, error) {
	ret := _m.Called(tenantID, version)

	if len(ret) == 0 {
		panic("no return value specified for KnowledgeBase")
	}

	var r0 *ast.KnowledgeBase
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*ast.KnowledgeBase, error)); ok {
		return rf(tenantID, version)
	}
	if rf, ok := ret.Get(0).(func(string, string) *ast.KnowledgeBase); ok {
		r0 = rf(tenantID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ast.KnowledgeBase)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(tenantID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KnowledgeBaseProvider_KnowledgeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KnowledgeBase'
type KnowledgeBaseProvider_KnowledgeBase_Call struct {
	*mock.Call
}

// KnowledgeBase is a helper method to define mock.On call
//   - tenantID string
//   - version string
func (_e *KnowledgeBaseProvider_Expecter) KnowledgeBase(tenantID interface{}, version interface{}) *KnowledgeBaseProvider_KnowledgeBase_Call {
	return &KnowledgeBaseProvider_KnowledgeBase_Call{Call: _e.mock.On("KnowledgeBase", tenantID, version)}
}

func (_c *KnowledgeBaseProvider_KnowledgeBase_Call) Run(run func(tenantID string, version string)) *KnowledgeBaseProvider_KnowledgeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *KnowledgeBaseProvider_KnowledgeBase_Call) Return(_a0 *ast.KnowledgeBase, _a1 error) *KnowledgeBaseProvider_KnowledgeBase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KnowledgeBaseProvider_KnowledgeBase_Call) RunAndReturn(run func(string, string) (*ast.KnowledgeBase, error)) *KnowledgeBaseProvider_KnowledgeBase_Call {
	_c.Call.Return(run)
	return _c
}

// NewKnowledgeBaseProvider creates a new instance of KnowledgeBaseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKnowledgeBaseProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *KnowledgeBaseProvider {
	mock := &KnowledgeBaseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
