// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	ast "github.com/hyperjumptech/grule-rule-engine/ast"
	mock "github.com/stretchr/testify/mock"

	rulesengine "github.com/jenujari/go-astro-re/rules-engine"
)

// RuleExecutor is an autogenerated mock type for the RuleExecutor type
type RuleExecutor struct {
	mock.Mock
}

type RuleExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleExecutor) EXPECT() *RuleExecutor_Expecter {
	return &RuleExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dataCtx, kb
func (_m *RuleExecutor) Execute(dataCtx ast.IDataContext, kb *ast.KnowledgeBase) (rulesengine.ExecutionTrace, error) {
	ret := _m.Called(dataCtx, kb)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 rulesengine.ExecutionTrace
	var r1 error
	if rf, ok := ret.Get(0).(func(ast.IDataContext, *ast.KnowledgeBase) (rulesengine.ExecutionTrace, error)); ok {
		return rf(dataCtx, kb)
	}
	if rf, ok := ret.Get(0).(func(ast.IDataContext, *ast.KnowledgeBase) rulesengine.ExecutionTrace); ok {
		r0 = rf(dataCtx, kb)
	} else {
		r0 = ret.Get(0).(rulesengine.ExecutionTrace)
	}

	if rf, ok := ret.Get(1).(func(ast.IDataContext, *ast.KnowledgeBase) error); ok {
		r1 = rf(dataCtx, kb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RuleExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dataCtx ast.IDataContext
//   - kb *ast.KnowledgeBase
func (_e *RuleExecutor_Expecter) Execute(dataCtx interface{}, kb interface{}) *RuleExecutor_Execute_Call {
	return &RuleExecutor_Execute_Call{Call: _e.mock.On("Execute", dataCtx, kb)}
}

func (_c *RuleExecutor_Execute_Call) Run(run func(dataCtx ast.IDataContext, kb *ast.KnowledgeBase)) *RuleExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ast.IDataContext), args[1].(*ast.KnowledgeBase))
	})
	return _c
}

func (_c *RuleExecutor_Execute_Call) Return(_a0 rulesengine.ExecutionTrace, _a1 error) *RuleExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleExecutor_Execute_Call) RunAndReturn(run func(ast.IDataContext, *ast.KnowledgeBase) (rulesengine.ExecutionTrace, error)) *RuleExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRuleExecutor creates a new instance of RuleExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleExecutor {
	mock := &RuleExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
